### ISSUE TITLE
chess jar-file with win64 7 SP1

### ISSUE THREAD

**Issue by yellow-panther** [bruno-unna/chess#1]
Hello bruno-unna,

it seems that your jar-file executes no moves under Arena 3.5.1 GUI www.playwitharena.de respectively WinBoard AA beta http://hgm.nubati.net/WinBoard-AA.zip , or is your program at early development stage?

Regards,

**Comment by bruno-unna** [comment]
Hello @yellow-panther,

Thank you for taking the time to try it. Unfortunately, as you have already guessed, this program is in early stages of development. I've so far implemented the UCI, and I'm only starting the development of the actual engine.

The fact that you've tried it is encouraging. Kind regards.

**Comment by yellow-panther** [comment]
Hello bruno-unna,

for a later release it would be a good idea to mention which JRE versiom is (at least) required to run your engine - GUIs cf. http://www.computer-chess.org/doku.php?id=computer_chess:wiki:lists:gui_protocol_support_list Oracle Java website https://www.oracle.com/technetwork/java/javase/downloads/index.html

Regards,
